##############################################################################################################################
###############################################   FEATURE ABLATIONS    #######################################################
##############################################################################################################################
CPDB_cdgps_CNA:
  lr: 0.01
  lr_f: 0.005
  num_hidden: 64
  num_heads: 4
  num_layers: 3
  weight_decay: 1e-3
  weight_decay_f: 1e-4
  max_epoch: 100
  max_epoch_f: 200
  mask_rate: 0.5
  num_layers: 2
  encoder: rgcn
  decoder: rgcn 
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce 
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.05 
  alpha_l: 3
  scheduler: True
  logging: True
  num_edge_types: 6
  weight_decomposition: {'type': 'basis', 'num_bases': 2}
  vertical_stacking: True
CPDB_cdgps_GE:
  lr: 0.01
  lr_f: 0.005
  num_hidden: 64
  num_heads: 4
  num_layers: 3
  weight_decay: 1e-3
  weight_decay_f: 1e-4
  max_epoch: 100
  max_epoch_f: 200
  mask_rate: 0.5
  num_layers: 2
  encoder: rgcn
  decoder: rgcn 
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce 
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.05 
  alpha_l: 3
  scheduler: True
  logging: True
  num_edge_types: 6
  weight_decomposition: {'type': 'basis', 'num_bases': 2}
  vertical_stacking: True
CPDB_cdgps_METH:
  lr: 0.01
  lr_f: 0.005
  num_hidden: 64
  num_heads: 4
  num_layers: 3
  weight_decay: 1e-3
  weight_decay_f: 1e-4
  max_epoch: 100
  max_epoch_f: 200
  mask_rate: 0.5
  num_layers: 2
  encoder: rgcn
  decoder: rgcn 
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce 
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.05 
  alpha_l: 3
  scheduler: True
  logging: True
  num_edge_types: 6
  weight_decomposition: {'type': 'basis', 'num_bases': 2}
  vertical_stacking: True
CPDB_cdgps_MF:
  lr: 0.01
  lr_f: 0.005
  num_hidden: 64
  num_heads: 4
  num_layers: 3
  weight_decay: 1e-3
  weight_decay_f: 1e-4
  max_epoch: 100
  max_epoch_f: 200
  mask_rate: 0.5
  num_layers: 2
  encoder: rgcn
  decoder: rgcn 
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce 
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.05 
  alpha_l: 3
  scheduler: True
  logging: True
  num_edge_types: 6
  weight_decomposition: {'type': 'basis', 'num_bases': 2}
  vertical_stacking: True
CPDB_cdgps_CNA_GE_METH:
  lr: 0.01
  lr_f: 0.005
  num_hidden: 64
  num_heads: 4
  num_layers: 3
  weight_decay: 1e-3
  weight_decay_f: 1e-4
  max_epoch: 100
  max_epoch_f: 200
  mask_rate: 0.5
  num_layers: 2
  encoder: rgcn
  decoder: rgcn 
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce 
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.05 
  alpha_l: 3
  scheduler: True
  logging: True
  num_edge_types: 6
  weight_decomposition: {'type': 'basis', 'num_bases': 2}
  vertical_stacking: True
CPDB_cdgps_CNA_GE_MF:
  lr: 0.01
  lr_f: 0.005
  num_hidden: 64
  num_heads: 4
  num_layers: 3
  weight_decay: 1e-3
  weight_decay_f: 1e-4
  max_epoch: 100
  max_epoch_f: 200
  mask_rate: 0.5
  num_layers: 2
  encoder: rgcn
  decoder: rgcn 
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce 
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.05 
  alpha_l: 3
  scheduler: True
  logging: True
  num_edge_types: 6
  weight_decomposition: {'type': 'basis', 'num_bases': 2}
  vertical_stacking: True
CPDB_cdgps_CNA_METH_MF:
  lr: 0.01
  lr_f: 0.005
  num_hidden: 64
  num_heads: 4
  num_layers: 3
  weight_decay: 1e-3
  weight_decay_f: 1e-4
  max_epoch: 100
  max_epoch_f: 200
  mask_rate: 0.5
  num_layers: 2
  encoder: rgcn
  decoder: rgcn 
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce 
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.05 
  alpha_l: 3
  scheduler: True
  logging: True
  num_edge_types: 6
  weight_decomposition: {'type': 'basis', 'num_bases': 2}
  vertical_stacking: True
CPDB_cdgps_GE_METH_MF:
  lr: 0.01
  lr_f: 0.005
  num_hidden: 64
  num_heads: 4
  num_layers: 3
  weight_decay: 1e-3
  weight_decay_f: 1e-4
  max_epoch: 100
  max_epoch_f: 200
  mask_rate: 0.5
  num_layers: 2
  encoder: rgcn
  decoder: rgcn 
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce 
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.05 
  alpha_l: 3
  scheduler: True
  logging: True
  num_edge_types: 6
  weight_decomposition: {'type': 'basis', 'num_bases': 2}
  vertical_stacking: True
CPDB_cdgps_random_features:
  lr: 0.01
  lr_f: 0.005
  num_hidden: 64
  num_heads: 4
  num_layers: 3
  weight_decay: 1e-3
  weight_decay_f: 1e-4
  max_epoch: 100
  max_epoch_f: 200
  mask_rate: 0.5
  num_layers: 2
  encoder: rgcn
  decoder: rgcn 
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce 
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.05 
  alpha_l: 3
  scheduler: True
  logging: True
  num_edge_types: 6
  weight_decomposition: {'type': 'basis', 'num_bases': 2}
  vertical_stacking: True