experiment_type: feature_ablations
base_ppi: CPDB

datasets:
  - name: CPDB_cdgps_CNA_GE_METH_MF
    description: All features (CNA, GE, METH, MF)
  - name: CPDB_cdgps_random_features
    description: Random features
  - name: CPDB_cdgps_CNA
    description: Only CNA features
  - name: CPDB_cdgps_GE
    description: Only GE features
  - name: CPDB_cdgps_METH
    description: Only METH features
  - name: CPDB_cdgps_MF
    description: Only MF features
  - name: CPDB_cdgps_CNA_GE
    description: CNA and GE features
  - name: CPDB_cdgps_CNA_METH
    description: CNA and METH features
  - name: CPDB_cdgps_CNA_MF
    description: CNA and MF features
  - name: CPDB_cdgps_GE_METH
    description: GE and METH features
  - name: CPDB_cdgps_GE_MF
    description: GE and MF features
  - name: CPDB_cdgps_METH_MF
    description: METH and MF features
  - name: CPDB_cdgps_CNA_GE_METH
    description: CNA, GE, and METH features
  - name: CPDB_cdgps_CNA_GE_MF
    description: CNA, GE, and MF features
  - name: CPDB_cdgps_CNA_METH_MF
    description: CNA, METH, and MF features
  - name: CPDB_cdgps_GE_METH_MF
    description: GE, METH, and MF features

# Model parameters
num_hidden: 64
num_heads: 4
num_layers: 2
encoder: rgcn
decoder: rgcn
activation: prelu
in_drop: 0.2
attn_drop: 0.1
weight_decomposition: {"type": "basis", "num_bases": 2}
vertical_stacking: "True"
num_edge_types: 6

# Training parameters
lr: 0.01
lr_f: 0.005
weight_decay: 1e-3
weight_decay_f: 1e-4
max_epoch: 100
max_epoch_f: 200
mask_rate: 0.5
drop_edge_rate: 0.0
replace_rate: 0.05
alpha_l: 3
linear_prob: "False"
loss_fn: sce
optimizer: adam
scheduler: "False"
logging: "True"

# Model saving parameters
save_model: "True"
save_dir: "checkpoints"

# Data parameters
# batch_size: 64
# validation_split: 0.2
# test_split: 0.2
# seeds: [0,1,2]
# num_iterations: 3 